const GET_VIDEOGAMES = "GET_VIDEOGAMES";
const GET_DETAILVIDEOGAME = "GET_DETAILVIDEOGAME";
const GET_VIDEOGAMESBYNAME = "GET_VIDEOGAMESBYNAME";

export { GET_VIDEOGAMES, GET_DETAILVIDEOGAME, GET_VIDEOGAMESBYNAME };
