const GET_VIDEOGAMES = "GET_VIDEOGAMES";
const GET_DETAILVIDEOGAME = "GET_DETAILVIDEOGAME";
const GET_VIDEOGAMESBYNAME = "GET_VIDEOGAMESBYNAME";
const ORDER_BY_RATING = "ORDER_BY_RATING";
const ORDER_BY_NAME = "ORDER_BY_NAME";
const FILTER_BY_GENRES = "FILTER_BY_GENRES";

export {
  GET_VIDEOGAMES,
  GET_DETAILVIDEOGAME,
  GET_VIDEOGAMESBYNAME,
  ORDER_BY_RATING,
  FILTER_BY_GENRES,
  ORDER_BY_NAME,
};
